version: "3.3"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    env_file: .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
