apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName | default "notification-service" }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerClass: metallb.io/loadbalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP | default "192.168.1.204" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.appName | default "notification-service" }}
    color: {{ .Values.color }}
