apiVersion: v1
kind: Service
metadata:
  name: {{ include "room-mgmt-service.fullname" . }}-preview
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "room-mgmt-service.name" . }}
