apiVersion: v1
kind: Service
metadata:
  name: {{ include "room-mgmt-service.fullname" . }}
  labels:
    app: {{ include "room-mgmt-service.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "room-mgmt-service.name" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "room-mgmt-service.fullname" . }}-preview
  labels:
    app: {{ include "room-mgmt-service.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "room-mgmt-service.name" . }}
