replicaCount: 1
appName: notification-service

image:
  repository: sujan1234ray/notification-service
  pullPolicy: IfNotPresent
  tag: "latest"

color: blue

service:
  type: LoadBalancer
  port: 80
  targetPort: 3004
  loadBalancerIP: 192.168.1.204

env:
  NODE_ENV: "production"
  PORT: "3004"
  HOST: "0.0.0.0"
  EMAIL_DOMAIN: "mail.pokharelsujan.info.np"

secrets:
  RESEND_API_KEY: ""
  AUTH_HEADER_KEY: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 3004
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: 3004
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

imagePullSecrets:
  - name: docker-hub-credentials

nodeSelector:
  kubernetes.io/arch: arm64

tolerations: []
affinity: {}
