replicaCount: 1

appName: notification-service

image:
  repository: sujan1234ray/notification-service
  tag: "latest"

color: blue

service:
  targetPort: 3004

env:
  NODE_ENV: "production"
  PORT: "3004"
  EMAIL_DOMAIN: "mail.pokharelsujan.info.np"

secrets:
  RESEND_API_KEY: ""
  AUTH_HEADER_KEY: ""
