replicaCount: 1

appName: room-management-service

image:
  repository: sujan1234ray/room-management-service
  pullPolicy: IfNotPresent
  tag: "latest"

color: blue

service:
  type: LoadBalancer
  port: 80
  targetPort: 3002
  serviceName: room-management-service
  loadBalancerIP: 192.168.1.201  # Fixed external IP
  nodePort: 30081                # Fixed NodePort (optional)
  

# Environment variables for ConfigMap
env:
  CORS_ORIGINS: "http://localhost:4200,https://pokharelsujan.info.np"
  PORT: "3002"
  HOST: "0.0.0.0"
  DB_MODE: "cloud"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "neondb"
  DB_SCHEMA: "REALSTATE"
  LOGIN: "LOGIN_TABLE"
  USER_PROFILE: "USER_PROFILE_TABLE"
  CLIENT_ID: "539011910849-qk1h6i9c5t9d0bn094jaa9q6rt2k7amu.apps.googleusercontent.com"
  REDIRECT_URI: "http://localhost:8000/oauth2callback"
  JWT_EXPIRATION: "10m"
  NODE_ENV: "production" # Will be overridden by Jenkins

# Sensitive variables for Secret
secrets:
  JWT_SECRET: ""
  DB_PASSWORD: ""
  DATABASE_URL: ""
  CLIENT_SECRET: ""
  ACCESS_TOKEN: ""
  REFRESH_TOKEN: ""
  EXPIRY_DATE: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3002
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: 3002
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

imagePullSecrets:
- name: docker-hub-credentials

nodeSelector:
  kubernetes.io/arch: arm64

tolerations: []

affinity: {}
